package com.jpmorgan.orderbook;

public enum OrderState {
    PLACE_ACKED, CANCEL_ACKED, AMEND_PRICE_ACKED, AMEND_QUANTITY_ACKED,
    PLACE_REJECTED, CANCEL_REJECTED, AMEND_PRICE_REJECTED, AMEND_QUANTITY_REJECTED
}
